#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16
#define LV_DPI_DEF 130
#define LV_DEF_REFR_PERIOD 16

#define LV_USE_STDLIB_MALLOC LV_STDLIB_BUILTIN
#define LV_USE_STDLIB_STRING LV_STDLIB_BUILTIN
#define LV_USE_STDLIB_SPRINTF LV_STDLIB_BUILTIN
#define LV_MEM_SIZE (256U * 1024U)
#define LV_MEM_POOL_EXPAND_SIZE 0
#define LV_USE_OS LV_OS_NONE

#define LV_USE_LOG 0
#define LV_USE_ASSERT_NULL 1
#define LV_USE_ASSERT_MALLOC 1
#define LV_USE_ASSERT_STYLE 0
#define LV_USE_ASSERT_MEM_INTEGRITY 0
#define LV_USE_ASSERT_OBJ 0

#define LV_DRAW_SW_DRAW_UNIT_CNT 1
#define LV_DRAW_SW_COMPLEX 1
#define LV_DRAW_SW_SHADOW_CACHE_SIZE 16
#define LV_DRAW_SW_CIRCLE_CACHE_SIZE 8
#define LV_USE_DRAW_SW_COMPLEX_GRADIENTS 0

#define LV_FONT_MONTSERRAT_14 0
#define LV_FONT_UNSCII_8 0
#define LV_FONT_CUSTOM_DECLARE extern const lv_font_t *oos_lvgl_default_font;
#define LV_FONT_DEFAULT oos_lvgl_default_font
#define LV_USE_FONT_COMPRESSED 0

#define LV_USE_FS_STDIO 1
#define LV_FS_STDIO_LETTER 'A'
#define LV_FS_STDIO_PATH ""
#define LV_USE_TINY_TTF 1
#define LV_TINY_TTF_FILE_SUPPORT 1
#define LV_TINY_TTF_CACHE_GLYPH_CNT 16
#define LV_TINY_TTF_CACHE_KERNING_CNT 32

#define LV_USE_THEME_DEFAULT 1
#define LV_THEME_DEFAULT_DARK 1
#define LV_THEME_DEFAULT_GROW 0
#define LV_THEME_DEFAULT_TRANSITION_TIME 0

#define LV_USE_FLEX 1
#define LV_USE_GRID 1
#define LV_USE_TRANSLATION 0
#define LV_USE_XML 0
#define LV_BUILD_EXAMPLES 0
#define LV_BUILD_DEMOS 0

#endif
