# SDL key name = Linux/OOS T9 key name
0 = KEY_0
1 = KEY_1
2 = KEY_2
3 = KEY_3
4 = KEY_4
5 = KEY_5
6 = KEY_6
7 = KEY_7
8 = KEY_8
9 = KEY_9

Return = KEY_OK
Keypad Enter = KEY_OK
Backspace = KEY_BACK
Q = KEY_MENU
W = KEY_OPTION

Up = KEY_UP
Down = KEY_DOWN
Left = KEY_LEFT
Right = KEY_RIGHT
Escape = KEY_BACK
Keypad * = KEY_NUMERIC_STAR
Keypad # = KEY_NUMERIC_POUND
